version: '2'

services:
  web:
    command: node index.js
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "${PORT}"
    links:
      - mongo
    environment:
      - MONGO_DB_URI="${MONGO_DB_URI}"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata

  mongodata:
    image: tianon/true
    volumes:
      - /data/db
